=== gridaco/grida/apps/forms/public/schema/form.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://forms.grida.co/schema/form.schema.json",
  "title": "Form",
  "description": "A form schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "description": "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#name"
    },
    "description": {
      "type": "string"
    },
    "action": {
      "type": "string",
      "format": "uri",
      "description": "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#action"
    },
    "enctype": {
      "type": "string",
      "enum": [
        "application/x-www-form-urlencoded",
        "multipart/form-data",
        "text/plain"
      ],
      "default": "application/x-www-form-urlencoded",
      "description": "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#enctype"
    },
    "method": {
      "type": "string",
      "enum": ["get", "post", "dialog"],
      "default": "get",
      "description": "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#method"
    },
    "novalidate": {
      "type": "boolean",
      "default": false,
      "description": "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#novalidate"
    },
    "target": {
      "type": "string",
      "enum": ["_self", "_blank", "_parent", "_top"],
      "default": "_self",
      "description": "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#target"
    },
    "fields": {
      "type": "array",
      "items": {
        "$ref": "https://forms.grida.co/schema/field.schema.json"
      }
    }
  },
  "required": ["name"]
}

=== gridaco/grida/editor/public/schema/examples/007-data-transform/form.json
{
  "$schema": "https://grida.co/schema/form.schema.json",
  "title": "Data Transform",
  "name": "Data Transform",
  "description": "merge fields to construct a json data",
  "method": "post",
  "fields": [
    {
      "name": "data.$.preference.language",
      "label": "Language (preference.language)",
      "placeholder": "Your language",
      "required": true,
      "type": "select",
      "options": [
        {
          "label": "🇺🇸 English",
          "value": "en"
        },
        {
          "label": "🇯🇵 Japanese",
          "value": "ja"
        },
        {
          "label": "🇪🇸 Spanish",
          "value": "es"
        },
        {
          "label": "🇫🇷 French",
          "value": "fr"
        },
        {
          "label": "🇰🇷 Korean",
          "value": "ko"
        },
        {
          "label": "🇩🇪 German",
          "value": "de"
        },
        {
          "label": "🇮🇹 Italian",
          "value": "it"
        },
        {
          "label": "🇷🇺 Russian",
          "value": "ru"
        },
        {
          "label": "🇵🇹 Portuguese",
          "value": "pt"
        },
        {
          "label": "🇳🇱 Dutch",
          "value": "nl"
        },
        {
          "label": "🇹🇷 Turkish",
          "value": "tr"
        },
        {
          "label": "🇸🇪 Swedish",
          "value": "sv"
        },
        {
          "label": "🇩🇰 Danish",
          "value": "da"
        },
        {
          "label": "🇫🇮 Finnish",
          "value": "fi"
        },
        {
          "label": "🇳🇴 Norwegian",
          "value": "no"
        },
        {
          "label": "🇮🇩 Indonesian",
          "value": "id"
        },
        {
          "label": "🇲🇾 Malay",
          "value": "ms"
        },
        {
          "label": "🇵🇭 Filipino",
          "value": "fil"
        },
        {
          "label": "🇻🇳 Vietnamese",
          "value": "vi"
        },
        {
          "label": "🇹🇭 Thai",
          "value": "th"
        }
      ]
    },
    {
      "name": "data.$.user.name",
      "label": "Name (user.name)",
      "placeholder": "Your name",
      "required": true,
      "type": "text"
    },
    {
      "name": "data.$.user.age",
      "label": "Age (user.age)",
      "placeholder": "Your age",
      "required": true,
      "type": "range"
    },
    {
      "name": "data.$.user.tags",
      "label": "Tags (user.tags)",
      "placeholder": "Your tags",
      "required": true,
      "type": "toggle-group",
      "multiple": true,
      "options": [
        {
          "label": "🍔",
          "value": "burger"
        },
        {
          "label": "🍟",
          "value": "fries"
        },
        {
          "label": "🍦",
          "value": "ice-cream"
        }
      ]
    }
  ]
}
